# Generated by Django 6.0.4 on 2026-05-08 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_booking_comment_booking_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
